apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-demo
  template:
    metadata:
      labels:
        app: aks-demo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: aks-demo
        image: azacrdm1.azurecr.io/fastapipydiator:v1
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: aks-demo
spec:
  ports:

 - protocol: TCP

   port: 80

   name: https

   targetPort: 8081
  selector:
    app: aks-demo
